---
title: "PS1_datahandling"
author: "Max Yamamoto"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(quantmod)
library(rvest)

start_date <- ymd("2001-01-01")
end_date <- ymd("2015-12-31")

get_stock_price_data <- function(code, start_date, end_date) {
  data <-
    try(
      getSymbols(code, auto.assign = FALSE),
      silent = TRUE)

  if (any(class(data) %in% "try-error")) {
    return(NULL)}

  data <-
    data |>
    data.frame() |>
    rownames_to_column("date") |>
    tibble() |>
    rename(open = 2, high = 3, low = 4, close = 5, volume = 6, adjusted = 7) |>
    mutate(return = close / lag(close, 1) - 1)

  return(data)
}

sp500_url <- 'https://en.wikipedia.org/wiki/List_of_S%26P_500_companies'

stock_data <-
  read_html(sp500_url) |> 
  html_node('#constituents') |>
  html_table() |> 
  mutate(price =  map(Symbol, ~get_stock_price_data(., start_date, end_date)))

dat_all <- 
  stock_data |> 
  unnest(price) |> 
  select(date, code = Symbol, ret = return) |> 
  mutate(date = ymd(date)) |> 
  drop_na() 

dat_all <- 
  dat_all |> 
  mutate(date = ceiling_date(date, "month") - 1) |> 
  group_by(date, code) |> 
  summarise(ret = prod(1 + ret) - 1) |> 
  arrange(code, date)
```
# The power of diversification
Construct portfolios with 5, 10, ... stocks and calculate average and standard deviation of equal weighted portfolios' returns.

```{r}
filter_port <- function(num, dat_all){
  results <- 
    dat_all |> 
    filter(code %in%  
             (dat_all |> 
                ungroup() |> 
                distinct(code) |> 
                head(num) |> 
                pull(code)))
  return(results)
}

calc_port_ret <- function(dat_filtered){
  results <- 
    dat_filtered |> 
    group_by(date) |> 
    summarise(port_ret = mean(ret))
  return(results)
} 

calc_stats <- function(dat_port){ 
  results <- 
    dat_port |> 
    summarise(average = mean(port_ret),
              std = sd(port_ret))
  return(results)
}

calc_ind_std <- function(dat_filtered){
  results <- 
    dat_filtered |> 
    group_by(code) |> 
    summarise(std = sd(ret)) |> 
    ungroup() |> 
    summarise(contribution = (sum(std^2) / (n()^2))^(1/2)) |> 
    pull(contribution)
  return(results)
}

port_stats <- 
  seq(5, nrow(stock_data), 5) |> 
  enframe() |> 
  mutate(dat_filtered = map(value, ~filter_port(., dat_all)),
         port_ret = map(dat_filtered, ~calc_port_ret(.)), 
         stats = map(port_ret, ~calc_stats(.)),
         individual_std = map_dbl(dat_filtered, ~calc_ind_std(.)) )  |> 
  unnest(stats) |> 
  mutate(contri_cov = std - individual_std)

port_stats |> 
  ggplot() +
  aes(x = value, y = std) +
  geom_point() +
  geom_smooth() +
  labs(x = "number of stocks in a portfolio",
       y = "standard deviation",
       title = "Diversification reduces risk")
  
```

```{r}
port_stats |> 
  ggplot() +
  aes(x = value, y = average) +
  geom_point() +
  geom_smooth() +
  labs(x = "number of stocks in a portfolio",
       y = "average return",
       title = "Diversification does not improve return")
```

```{r}
port_stats |> 
  ggplot() + 
  aes(x = std, y = average, color = value) +
  geom_point() +
  labs(x = "standard deviation",
       y = "average return",
       color = "number of stocks in a portfolio",
       title = "Diversification improves(stabilizes) Sharpe Ratio")
```
# Contributions by individual variances and covariances

```{r}
port_stats |> 
  select(num_stock = value,individual_std, contri_cov) |> 
  pivot_longer(cols = -num_stock) |> 
  ggplot() +
  aes(x = num_stock, y = value, fill = name,) +
  geom_bar(stat = "identity") +
  labs(y = "volatility", fill = "")
 
```
